version: '3.7'
services:
  exam-api:
    build: .
    image: 'exam-api:latest'
    container_name: exam-api
    networks:
      - saba
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: unless-stopped
networks:
  saba:
    external:
      name: saba
