version: '3.7'
services:
  exam-api:
    build: .
    image: 'exam-api:latest'
    container_name: exam-api
    networks:
      - saba
    environment:
      - MONGO_CONNECTION=mongodb://mongo/steel_company
      - PORT=80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: unless-stopped
networks:
  saba:
    external:
      name: saba


# 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