version: '3.7'
services:
  exam-api:
    build: .
    image: 'exam-api:latest'
    container_name: exam-api
    networks:
      - saba
    environment:
      - MONGO_CONNECTION=mongodb://mongodbContainer/steel_company
      - PORT=80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: unless-stopped

  mongodbContainer:
    image: mongo:4.2.5
    container_name: mongodbContainer
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: bia2aroosi
    volumes:
      - mongodb_vol:/data/db
    networks:
      - saba

volumes:
  bia2aroosi_backend_vol:
  mongodb_vol:

networks:
  saba:
    external:
      name: saba


# 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