export enum PhotoType {
  PHOTO3IN4 = 'PHOTO3IN4',
  CERTIFICATE = 'CERTIFICATE',
  DESCRIPTION_PAGE = 'DESCRIPTION_PAGE',
  NATIONAL_CARD = 'NATIONAL_CARD',
  EDUCATION_DEGREE = 'EDUCATION_DEGREE',
  LICENSE = 'LICENSE',
  SACRIFICE = 'SACRIFICE',
  INSURANCE = 'INSURANCE',
  STUDENT = 'STUDENT',
  RESUME = 'RESUME',
}
